config/routes.rb
Rails.application.routes.draw do
  mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql#execute" if Rails.env.development?
  post "/graphql", to: "graphql#execute"
  namespace :line do
    get 'authentications/link'
    get 'authentications/create'
  end
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'homes#index'
  post '/homes/guest_sign_in', to: 'homes#guest_sign_in'
  get 'terms', to: 'homes#terms'
  get 'privacy', to: 'homes#privacy'

  resources :schedules, except: %i[show]

  resources :contents, except: %i[show edit]

  resource :profile, only: %i[show edit update]

  devise_scope :user do
    get '/users', to: 'users/registrations#new'
  end

  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    sessions: "users/sessions",
  }

  namespace :line do
    get 'link', to: 'authentications#link'
    post 'link', to: 'authentications#create'
    post '/callback', to: 'line_bot#callback'
    resources :flags, only: %i[create destroy]
    resources :notifications, only: %i[create]
  end

  namespace :api do
    resources :contents, only: [:index]
  end
end

app/models/content.rb
class Content < ApplicationRecord
  has_one :schedule, -> { order(position: :asc) }, dependent: :destroy
  has_many :user_contents, dependent: :destroy
  has_many :users, through: :user_contents
  has_many :line_flags, dependent: :destroy
  belongs_to :master

  enum stream: { default: 0, Mon: 1, Tue: 2, Wed: 3, Thu: 4, Fri: 5, Sat: 6, Sun: 7 }
  enum media: [ "Abemaビデオ", "Amazonプライム", "Netflix" ]

  validates :title, presence: true, length: { maximum: 255 }
  validates :media, presence: true, length: { maximum: 100 }
  validates :url, presence: true, length: { maximum: 2048 }
  validates :stream, presence: true

  scope :registered, -> { where(registered: true) }
  scope :unregistered, -> { where(registered: false) }
  scope :unwatched, -> { where(new_flag: true) }

  def register
    update(registered: true)
  end

  def unregister
    update(registered: false)
  end

  def flag_off
    update(new_flag: false)
  end

  def line_on
    update(line_flag: true)
  end

  def line_off
    update(line_flag: false)
  end

  def self.create_from_masters(master_ids, current_user)
    master_ids.each do |master_id|
      master = Master.find(master_id.to_i)
      content = current_user.contents.create!(title: master.title, media: master.media, url: master.url, stream: master.stream, registered: false, new_flag: true, episode: master.episode, master_id: master.id)
      unless current_user.limit_position(content.stream)
        current_user.schedules.create(content_id: content.id, day: content.stream)
        content.register
      end
    end
  end
end

app/controllers/api/contents_controller.rb
module Api
  class ContentsController < ApplicationController
    skip_before_action :verify_authenticity_token

    def index
      if current_user
        contents = current_user.contents.order(stream: :asc)
        render json: { contents: }
      else
        render json: { message: 'ログインしてください' }
      end
    end
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :authenticate_user!

  def index
    @contents = current_user.contents.order(stream: :asc)
  end

  def new
    @content = Content.new
    @contents = current_user.contents
  end

  def create
    master_ids = params[:content][:master_id]
    Content.create_from_masters(master_ids, current_user)
    flash[:success] = "#{master_ids.size}件のタイトルと時間割を登録しました"
    redirect_to contents_path
  end

  def update
    @content = current_user.contents.find(params[:id])
    @content.flag_off
  end

  def destroy
    @content = current_user.contents.find(params[:id])
    respond_to do |format|
      if @content.destroy
        format.js
      else
        flash.now[:danger] = "削除に失敗しました"
        render :index
      end
    end
  end

  private

  def content_params
    params.require(:content).permit(:title, :media, :url, :stream, :new_flag, :episode, :line_flag, :master_id => [])
  end
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/_content.html.erb
<div id="content-card<%= content.id %>" class="col-md-4 card-md-4">
  <div class="card h-100">
    <div class="card-header" id="<%= content.decorate.media_color %>"><%= content.title.truncate(18) %></div>
    <div class="card-body" id="content-card-body">
      <%= link_to content_path(content), method: :delete, remote: true do %><i class="far fa-trash-alt fa-lg"></i><% end %>
      <p class="card-text"><%= content.stream_i18n %>曜配信</p>
      <% if content.line_flag %>
        <div id="line-flag<%= content.id %>"><%= link_to line_flag_path(id: content.id), :method => :delete, remote: true do %><div class="btn btn-success">LINE通知オン</div><% end %></div>
      <% else %>
        <div id="line-flag<%= content.id %>"><%= link_to line_flags_path(id: content.id), :method => :post, remote: true do %><div class="btn btn-secondary">LINEで通知する</div><% end %></div>
      <% end %>
    </div>
    <div class="card-footer">
      <%= link_to content.url, target: :_blank, rel: "noopener noreferrer", class: "media-link" do %><%= content.media %>で観る<i class="fas fa-external-link-alt" style="padding-left: 5px;"></i><% end %>
    </div>
  </div>
</div>

app/views/contents/create.js.erb
console.log('create');
$("#t-header").after("<%= j (render 'content', content: @content) %>");
$("#content-modal").modal("hide");

app/views/contents/destroy.js.erb
$("#content-card<%= @content.id %>").remove();

app/views/contents/index.html.erb
<p id="to-schedules-link"><%= link_to "<< 時間割リストへ", schedules_path, style: "color: gray;" %></p>
<div class="row">
  <div class="col-lg-6">
    <div id="media-add-area">
      <span class="box-title">タイトル登録</span>
        <div id="add-content">
          <span><%= link_to "Abema", new_content_path(media: "Abemaビデオ"), class: "btn btn-dark" %></span>
          <span><%= link_to "Amazon", new_content_path(media: "Amazonプライム"), class: "btn btn-primary" %></span>
          <span><%= link_to "Netflix", new_content_path(media: "Netflix"), class: "btn btn-danger" %></span>
        </div>
    </div>
  </div>
  <div class="col-lg-6">
    <div id="line-add-area">
      <span class="box-title">LINEで最新話通知を受け取る</span>
        <div id="add-line-friend">
          <a href="https://lin.ee/jWV0dpB"><img src="https://scdn.line-apps.com/n/line_add_friends/btn/ja.png" alt="友だち追加" height="36" border="0"></a>
        </div>
    </div>
  </div>
</div>
<div id="content-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

<div class="card-group">
  <div class="row">
    <%= render @contents %>
  </div>
</div>

app/views/contents/master.html.erb
<%= form_with(model: @content) do |f| %>
    <% if @content.errors.any? %>
    <div id="error_explanation">
      <h2 style="padding: 15px;"><%= pluralize(@content.errors.count, "件の入力エラー") %>:</h2>
      <ul>
        <% @content.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <div class="modal-header">
      <h5 class="modal-title">Amazonプライムのタイトル登録</h5>
      <%= f.submit class: "btn btn-primary"%>
    </div>
    <div class="modal-body">
        <%= f.collection_check_boxes :master_id, Master.all.where(media: "Amazonプライム").order(rank: :asc), :id, :title, include_hidden: false do |master| %>
        <p>
          <%= master.check_box %>
          <%= master.text %>
        </p>
        <% end %>
    </div>
    <% end %>

app/views/contents/netflix_list.html.erb
<%= form_with(model: @content) do |f| %>
    <% if @content.errors.any? %>
    <div id="error_explanation">
      <h2 style="padding: 15px;"><%= pluralize(@content.errors.count, "件の入力エラー") %>:</h2>
      <ul>
        <% @content.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <div class="modal-header">
      <h5 class="modal-title">Netflix</h5>
      <%= f.submit class: "btn btn-primary" %>
    </div>
    <div class="modal-body">
        <%= f.collection_check_boxes :master_id, Master.netflix_titles.onair.order(rank: :asc), :id, :title, include_hidden: false do |master| %>
        <p>
          <%= master.check_box %>
          <%= master.text %>
        </p>
        <% end %>
    </div>
    <% end %>

<script>
<% @contents.each do |content| %>
  $('#<%= "content_master_id_" + "#{content.master_id}" %>').parent().hide();
<% end %>
</script>

app/views/contents/new.html.erb
<%= form_with(model: @content) do |f| %>
    <% if @content.errors.any? %>
    <div id="error_explanation">
      <h2 style="padding: 15px;"><%= pluralize(@content.errors.count, "件の入力エラー") %>:</h2>
      <ul>
        <% @content.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <div class="modal-header">
      <h5 class="modal-title"><%= params[:media] %></h5>
      <%= f.submit class: "btn btn-primary"%>
    </div>
    <div class="modal-body">
        <%= f.collection_check_boxes :master_id, Master.media_titles(params[:media]).onair.order(rank: :asc), :id, :title, include_hidden: false do |master| %>
        <p>
          <%= master.check_box %>
          <%= master.text %>
        </p>
        <% end %>
    </div>
    <% end %>

<script>
<% @contents.each do |content| %>
  $('#<%= "content_master_id_" + "#{content.master_id}" %>').parent().hide();
<% end %>
</script>

app/views/contents/update.js.erb
$('#new-flag<%= @content.schedule.id %>').remove();
$('#title-card<%= @content.schedule.id %>').removeClass('btn btn-primary');
$('#title-card<%= @content.schedule.id %>').addClass('btn btn-outline-secondary');