config/routes.rb
Rails.application.routes.draw do
  mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql#execute" if Rails.env.development?
  post "/graphql", to: "graphql#execute"
  namespace :line do
    get 'authentications/link'
    get 'authentications/create'
  end
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'homes#index'
  post '/homes/guest_sign_in', to: 'homes#guest_sign_in'
  get 'terms', to: 'homes#terms'
  get 'privacy', to: 'homes#privacy'

  resources :schedules, except: %i[show]

  resources :contents, except: %i[show edit]

  resource :profile, only: %i[show edit update]

  devise_scope :user do
    get '/users', to: 'users/registrations#new'
  end

  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    sessions: "users/sessions",
  }

  namespace :line do
    get 'link', to: 'authentications#link'
    post 'link', to: 'authentications#create'
    post '/callback', to: 'line_bot#callback'
    resources :flags, only: %i[create destroy]
    resources :notifications, only: %i[create]
  end

  namespace :api do
    resources :contents, only: [:index]
  end
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :content
  belongs_to :user
  acts_as_list scope: [:day, :user_id]

  # validate :limit_position
  validates :day, presence: true
  validates :content_id, uniqueness: true

  scope :today, -> { where(day: Time.zone.today.strftime("%a")) }

  def no_position_error
    self.errors.add(:base, "時間割に空きがありません")
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :authenticate_user!
  def index
    @schedules = current_user.schedules.preload(:content)
  end

  def new
    @schedule = Schedule.new
    @contents = current_user.contents.unregistered
  end

  def edit
    @contents = current_user.contents
    @schedule = current_user.schedules.find(params[:id])
  end

  def create
    @contents = current_user.contents.unregistered
    @schedule = current_user.schedules.build(schedule_params)

    if current_user.limit_position(params[:schedule][:day])
      @schedule.no_position_error
      render :new
    else
      @schedule.save
      @contents.find(params[:schedule][:content_id]).register
      flash[:success] = "「#{@schedule.content.title}」を時間割登録しました"
      redirect_to schedules_path
    end
  end

  def update
    @contents = current_user.contents
    @schedule = current_user.schedules.find(params[:id])
    if current_user.limit_position(params[:schedule][:day])
      @schedule.no_position_error
      render :edit
    else
      @schedule.update(schedule_params)
      flash[:success] = t('.update.success', title: @schedule.content.title)
      redirect_to schedules_path
    end
  end

  def destroy
    schedule = current_user.schedules.find(params[:id])
    @content = current_user.contents.find(schedule.content_id)
    if schedule.destroy
      @content.unregister
      flash[:info] = t('.destroy.success', title: @content.title)
    else
      flash[:danger] = t('.destroy.failure')
    end
    redirect_to schedules_path
  end

  private

  def schedule_params
    params.require(:schedule).permit(:content_id, :day)
  end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_edit_form.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <%= form_with(model: @schedule) do |f| %>
    <% if @schedule.errors.any? %>
    <div id="error_explanation">
      <h2 style="padding: 15px;"><%= pluralize(@schedule.errors.count, "件の入力エラー") %>:</h2>
      <ul>
        <% @schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <div class="modal-header">
      <h5 class="modal-title">時間割編集</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <div class="form-group">
        <%= f.label :day, class: "form-control-label"%>
        <%= f.select :day, [["月","Mon"], ["火","Tue"], ["水","Wed"], ["木","Thu"], ["金","Fri"], ["土","Sat"], ["日","Sun"]], include_blank: "選択して下さい", class: "form-control" %>
      </div>
    </div>
    <div class="modal-footer actions">
      <%= f.submit class: "btn btn-primary"%>
      <% if @schedule.id %>
        <%= link_to "削除する", schedule_path(@schedule), method: :delete, data: { confirm: "削除しますか？" }, class: "btn btn-danger" %>
      <% end %>
    </div>
    <% end %>
  </div>
</div>

<style>
  .modal-dialog {
    max-width: inherit;
    width: 70%;
    margin: 0 auto;
    padding-top: 10%;
  }
</style>

app/views/schedules/_form.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <%= form_with(model: @schedule) do |f| %>
    <% if @schedule.errors.any? %>
    <div id="error_explanation">
      <h2 style="padding: 15px;"><%= pluralize(@schedule.errors.count, "件の入力エラー") %>:</h2>
      <ul>
        <% @schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <div class="modal-header">
      <h5 class="modal-title">New Schedule</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <div class="form-group">
        <%= f.label :content_id , class: "form-control-label"%>
        <%= f.collection_select :content_id, @contents, :id, :title, { prompt: "選択してください" }, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :day, class: "form-control-label"%>
        <%= f.select :day, [["月","Mon"], ["火","Tue"], ["水","Wed"], ["木","Thu"], ["金","Fri"], ["土","Sat"], ["日","Sun"]], include_blank: "選択して下さい", class: "form-control" %>
      </div>
    </div>
    <div class="modal-footer actions">
      <%= f.submit class: "btn btn-primary"%>
      <% if @schedule.id %>
        <%= link_to "削除する", schedule_path(@schedule), method: :delete, data: { confirm: "削除しますか？" }, class: "btn btn-danger" %>
      <% end %>
    </div>
    <% end %>
  </div>
</div>

<style>
  .modal-dialog {
    max-width: inherit;
    width: 70%;
    margin: 0 auto;
    padding-top: 10%;
  }
</style>

app/views/schedules/edit.js.erb
$("#schedule-modal").html("<%= escape_javascript(render 'edit_form') %>")
$("#schedule-modal").modal("show")

app/views/schedules/index.html.erb
<p id="to-contents-link"><%= link_to 'タイトルリストへ >>', contents_path, style: "color: gray;" %></p>

<div id="schedule-button">
  <p><%= link_to '時間割を追加する', new_schedule_path, remote: true, class: "btn btn-secondary", id: "add-schedule" %></p>
</div>

<div id="schedule-table-wrapper">
  <table class="table table-bordered table-responsive">
    <div id="content-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
    <div id="schedule-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
    <thead class="thead-dark">
      <tr>
        <th width="9%"></th>
        <th class="align-middle" width="13%" scope="col">月</th>
        <th class="align-middle" width="13%" scope="col">火</th>
        <th class="align-middle" width="13%" scope="col">水</th>
        <th class="align-middle" width="13%" scope="col">木</th>
        <th class="align-middle" width="13%" scope="col">金</th>
        <th class="align-middle" width="13%" scope="col">土</th>
        <th class="align-middle" width="13%" scope="col">日</th>
      </tr>
    </thead>
    <tbody>
    <% 1.upto(5) do |i| %>
      <tr>
        <th><%= i %></th>
        <td id="Mon<%= i %>" class="align-middle"></td>
        <td id="Tue<%= i %>" class="align-middle"></td>
        <td id="Wed<%= i %>" class="align-middle"></td>
        <td id="Thu<%= i %>" class="align-middle"></td>
        <td id="Fri<%= i %>" class="align-middle"></td>
        <td id="Sat<%= i %>" class="align-middle"></td>
        <td id="Sun<%= i %>" class="align-middle"></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

<script>
<% @schedules.each do |schedule| %>
  $('#<%= "#{schedule.day}" + "#{schedule.position}" %>').html('<div><%= link_to edit_schedule_path(schedule.id), remote: true do %><i class="far fa-edit float-right"></i><% end %></div>');
  <% if schedule.content.new_flag %>
    $('#<%= "#{schedule.day}" + "#{schedule.position}" %>').append('<div><%= link_to schedule.content.url, target: :_blank, rel: "noopener noreferrer", class: "btn btn-primary", id: "title-card#{schedule.id}" do %><p><%= schedule.content.title.truncate(15) %></p><% end %></div>');
  <% else %>
    $('#<%= "#{schedule.day}" + "#{schedule.position}" %>').append('<div><%= link_to schedule.content.url, target: :_blank, rel: "noopener noreferrer", class: "btn btn-outline-secondary" do %><p><%= schedule.content.title.truncate(15) %></p><% end %></div>');
  <% end %>
  <% if schedule.content.new_flag %>
    $('#<%= "#{schedule.day}" + "#{schedule.position}" %>').append('<div class="new-flag" id="new-flag<%= schedule.id %>"><%= "New! #{schedule.content.episode}話 " %><%= link_to content_path(schedule.content.id), :method => :patch, remote: true do %><%= image_tag 'viewed_button.png', class: "viewed-button" %><% end %></div>');
  <% end %>
<% end %>
</script>

app/views/schedules/new.js.erb
$("#schedule-modal").html("<%= escape_javascript(render 'form') %>")
$("#schedule-modal").modal("show")