config/routes.rb
Rails.application.routes.draw do
  mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql#execute" if Rails.env.development?
  post "/graphql", to: "graphql#execute"
  namespace :line do
    get 'authentications/link'
    get 'authentications/create'
  end
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'homes#index'
  post '/homes/guest_sign_in', to: 'homes#guest_sign_in'
  get 'terms', to: 'homes#terms'
  get 'privacy', to: 'homes#privacy'

  resources :schedules, except: %i[show]

  resources :contents, except: %i[show edit]

  resource :profile, only: %i[show edit update]

  devise_scope :user do
    get '/users', to: 'users/registrations#new'
  end

  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    sessions: "users/sessions",
  }

  namespace :line do
    get 'link', to: 'authentications#link'
    post 'link', to: 'authentications#create'
    post '/callback', to: 'line_bot#callback'
    resources :flags, only: %i[create destroy]
    resources :notifications, only: %i[create]
  end

  namespace :api do
    resources :contents, only: [:index]
  end
end

app/views/layouts/_google_analytics.html.erb
<!-- Global site tag (gtag.js) - Google Analytics -->
<% ga_id = ENV["GA_ID"] %>
<script async src="https://www.googletagmanager.com/gtag/js?id=<%= ga_id %>"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', ga_id);
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <%= display_meta_tags(default_meta_tags) %>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://kit.fontawesome.com/66cb772eea.js" crossorigin="anonymous"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <% if Rails.env.production? %>
    <%= render 'layouts/google_analytics' %>
  <% end %>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light" id="header-menu">
    <%= link_to "サブスクアニメ時間割", root_path, class: "navbar-brand", id: "title-logo" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
      aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
      <% if user_signed_in? %>
        <% unless current_user.guest %>
        <li class="nav-item">
          <%= link_to "マイページ", profile_path, class: "nav-link" %>
        </li>
        <% end %>
        <li class="nav-item">
          <%= link_to "時間割", schedules_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "タイトル一覧", contents_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" role="button"
            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            タイトル登録
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <%= link_to "Abemaから登録", new_content_path(media: "Abemaビデオ"), class: "dropdown-item" %>
            <%= link_to "Amazonから登録", new_content_path(media: "Amazonプライム"), class: "dropdown-item" %>
            <%= link_to "Netflixから登録", new_content_path(media: "Netflix"), class: "dropdown-item" %>
          </div>
        </li>
        <li class="nav-item">
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>  
        <li class="nav-item">
          <%= link_to "新規登録", new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "ログイン", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
      </ul>
    </div>
  </nav>
  <p><%= render 'shared/flash_message' %></p>
  <div class="wrapper">
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </div>
</body>

</html>